<?php
// $rootUrl = "http://localhost/github.com/atelierbram/atelierbramdehaan.nl/src/";
// $assetPath = "http://localhost/github.com/atelierbram/atelierbramdehaan.nl/docs/assets/";

$rootUrl = "https://atelierbramdehaan.nl/";
$assetPath = "https://atelierbramdehaan.nl/assets/";

// $env = "dev";
// $server = "local";

$env = "prod";
$server = "remote";

$siteTitle = "Atelier Bram de Haan";
$tagline = "Frontend Webdevelopment";
$img = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=";
?>
