<div id="page" class="site <?php if ($id == "siteIndex"): ?>is-language-en-hidden<?php endif; ?>">
  <div class="banner">
    <header class="site-header">
      <h1 class="site-header_title"><a class="logo" href="<?= $rootUrl ?>"><img data-src="<?= $assetPath ?>img/svg/atelierbramdehaan-logo-14-brando_768x384.svg?v1" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAABCAQAAABeK7cBAAAAC0lEQVR42mNkAAIAAAoAAv/lxKUAAAAASUVORK5CYII=" alt="logo Atelier Bram de Haan" class="logo_img" /><span class="screen-reader-text">Atelier </span><span class="logo_name screen-reader-text">Bram de Haan</span></a></h1>
      <p class="tagline screen-reader-text">2D Vormgeving</p>
    </header>
    <div class="theme-switch">
      <input class="theme-switch_toggle" id="themeSwitchToggle" type="checkbox">
      <label class="theme-switch_label" for="themeSwitchToggle"><svg width="20" height="20" fill="currentColor"><use xlink:href="#shape-sunmoon" /></svg><span class="screen-reader-text">licht of donker thema</span></label>
    </div>
  </div><!-- /.banner -->

