<div id="page" class="site">
  <div class="banner">
    <header class="site-header">
      <h1 class="site-header_title"><a class="logo" href="<?= $rootUrl ?>"><img data-src="<?= $assetPath ?>img/svg/abdh-redesign-logo-8_168x60.svg" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=" alt="logo Atelier Bram de Haan" class="logo_img" /><span class="screen-reader-text">Atelier </span><span class="logo_name f6">Bram de Haan</span></a></h1>
      <p class="tagline screen-reader-text">2D Vormgeving</p>
    </header>
    <!-- <nav class="site&#45;nav" id="siteNav"> -->
      <!-- <button class="menu-button" id="menuBtn"><span class="screen-reader-text">menu</span>
<svg class="svg-menu" width="42" height="36" fill="#454f5f"><use xlink:href="#shape-menu" /></svg></button> -->
      <!-- <ul class="site-nav_list" id="siteNavList"> -->
        <!--  <li class='nav-item < ?php if ($id == "webdesign") { echo "nav-item-current"; } ?>'><a href="< ?= $rootUrl;?>webdesign/">Webdesign</a></li> -->
          <!-- <li class='nav-item <?php // if ($id == "schilderijen") { echo "nav-item-current"; } ?>'><a href="< ?= $rootUrl;?>schilderijen/">Schilderijen</a></li> -->
          <!-- <li class='nav-item < ?php if ($id == "logos") { echo "nav-item-current"; } ?>'><a href="< ?= $rootUrl;?>logos/">Logo’s</a></li> -->
          <!-- <li class='nav-item <?php // if ($id == "bram") { echo "nav-item-current"; } ?>'><a href="< ?= $rootUrl;?>bram/">Bram</a></li> -->
     <!-- <li class='nav-item <?php // if ($id == "contact") { echo "nav-item-current"; } ?>'><a href="< ?= $rootUrl;?>contact/">Contact</a></li> -->
<!-- </ul> -->
    <!-- </nav> -->
    <div class="theme-switch">
      <input class="theme-switch_toggle" id="themeSwitchToggle" type="checkbox">
      <label class="theme-switch_label" for="themeSwitchToggle"><svg width="20" height="20" fill="currentColor"><use xlink:href="#shape-sunmoon" /></svg><span class="screen-reader-text">licht of donker thema</span></label>
    </div>
  </div><!-- /.banner -->

