<?php ?><div class="pagination row mb12">
<h5 class="pagination_prev pagination_item"><a href="<?= $prevLink; ?>" class="pagination_link"><span class="pagination_icon svg-icon"><svg width="16" height="16" fill="currentColor"><use xlink:href="#shape-arrow-prev"></svg></span><span class="pagination_text pagination_prev_text"><?= $prevText; ?></span></a></h5>
  <h5 class="pagination_next pagination_item"><a href="<?= $nextLink; ?>" class="pagination_link"><span class="pagination_text pagination_next_text"><?= $nextText; ?></span><span class="pagination_icon svg-icon"><svg width="16" height="16" fill="currentColor"><use xlink:href="#shape-arrow-next" /></svg></span></span></a></h5>
</div>

