<?php
$category = "ontwerk";
$attribute = "ontwikkeling";
$projectName = "Mediatheek SVDB";
$imageDescription = "deel van kop en navigatie menu van de mediatheek van Steunpunt Vluchtelingen De Bilt";
$projectDescription = "Mediatheek met ondersteunend lesmateriaal voor de taalcoaches en nieuwkomers van Steunpunt Vluchtelingen De Bilt";
?><li class="gallery_module mt8">
  <div class="gallery_module_header">
    <p class="f2"><?= $category ?> - <?= $attribute ?></p>
    <h3 class="gallery_module_header_title f2"><?= $projectName ?></h3>
  </div>
  <div class="gallery_module_media"><a href="<?= $rootUrl; ?>webdesign/mediatheek-steunpunt-vluchtelingen-de-bilt/"><img data-src="<?= $assetPath; ?>img/pics/webdesign/mediatheek-gallery_750x500.jpg" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='288' height='192' viewBox='0 0 288 192'%3E%3Crect width='288' height='192' fill='%23b5b0a6'/%3E%3C/svg%3E" alt="<?= $imageDescription; ?>" width="288" height="192" class="gallery_module_image"></a>
  </div>
  <div class="gallery_module_content">
    <p class="screen-reader-text"><?= $projectDescription ?></p>
  </div>
</li> 
