<?php ?><footer class="footer"><small>By <a href="http://atelierbramdehaan.nl">Bram de Haan</a></small></footer>
<?php // include "github-corner.inc"; ?>
<script><?php // include "loadCSS.js.inc"; ?></script>
<script src="http://localhost/~bram/bitbucket/bulsho/wp-content/themes/bulsho/src/colorscheme/assets/js/demo.min.js"></script>
<script src="../../docs/colorscheme/assets/js/demo.min.js"></script>
</body>
</html><?php ?>
