<?php ?>
<!doctype html>
<html lang="en" class="no-js core no-flexbox">
  <head>
    <meta charset="utf-8">
    <title>Colorscheme - <?= $title; ?></title>
    <meta name="description" content="<?= $description; ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../../build/colorscheme/assets/css/index.min.css" />
    <script><?php include "inc/head-detect.js.inc"; ?></script>
  </head>
  <body class="theme-<?= $id; ?>">

